config/routes.rb
Rails.application.routes.draw do

  get 'reviews/create'
	devise_for :customers

	get 'homes/top'
	root 'homes#top'

	get 'homes/about'
	get 'homes/author'

  	resources :customers, only: [:show, :edit, :update, :index] do
	  	member do
		  get 'mypage'
		  get 'unsubscribe'
		  patch 'unsubscribe'
		  get 'thanks'
		end
	end

	resources :posts do
		resources :post_comments, only: [:create, :destroy]
		resource  :favorites, only: [:create, :destroy]
		collection do
		  get 'all'
		  get 'ranking'
		end
	end

	resources :bookmarks, only: [:create, :destroy, :index]


	resources :reviews

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord

  belongs_to :customer
  belongs_to :post
  validates :customer_id, uniqueness: { scope: :post_id }

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, presence: true

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_posts, through: :bookmarks, source: :post
  has_many :post_comments, dependent: :destroy
  attachment :profile_image

end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :customer
	belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :customer
	has_many :favorites, dependent: :destroy
	has_many :favorited_customers, through: :favorites, source: :customer
	has_many :bookmarks, dependent: :destroy
	has_many :post_comments, dependent: :destroy
	attachment :product_image

	validates :rate, numericality: {
		less_than_or_equal_to: 5,
		greater_than_or_equal_to: 0
	}

	def favorited_by?(customer)
		favorites.where(customer_id: customer.id).exists?
	end

	def bookmark_by?(customer)
		bookmarks.where(customer_id: customer.id).exists?
	end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

	belongs_to :customer
	belongs_to :post

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [
			:last_name,
			:first_name,
			:last_name_kana,
			:first_name_kana,
			:handle_name
		])
	end

	def after_sign_in_path_for(reosurce)
		root_path(resource)
	end

	def after_sign_out_path_for(resource)
		root_path(resource)
	end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
  	#@customer = current_customer
  	#@bookmarks = Bookmark.where(customer_id: current_customer.id)
  	@bookmarks = Bookmark.where(customer_id: current_customer.id)
  	#@posts = Post.where(id: bookmarks)
  end

  def create
  	bookmark = current_customer.bookmarks.build(post_id: params[:post_id])
  	bookmark.customer_id = current_customer.id
    bookmark.save!
    redirect_to bookmarks_path
  end

  def destroy
  	current_customer.bookmarks.find_by(id: params[:id]).destroy!
    redirect_to bookmarks_path
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def mypage
    @customer = Customer.find(params[:id])
  end

  def show
    @customer = Customer.find(params[:id])
    @post = @customer.posts
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path(@customer)
    end
  end

  def index
    @customers = Customer.all
  end

  def unsubscribe
    @customer = Customer.find(params[:id])
    if request.patch?
      @customer.update(is_deleted: true)
      reset_session
      redirect_to thanks_customer_path
    end
  end

  def thanks
  end

  def customer_params
    params.require(:customer).permit(
      :last_name, :first_name, :last_name_kana, :first_name_kana, :handle_name, :email, :is_deleted, :profile_image)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
  	post = Post.find(params[:post_id])
	favorite = current_customer.favorites.new(post_id: post.id)
	favorite.save
	redirect_back(fallback_location: root_path)
  end

  def destroy
  	post = Post.find(params[:post_id])
	favorite = current_customer.favorites.find_by(post_id: post.id)
	favorite.destroy
	redirect_back(fallback_location: root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  	@posts = Post.order(created_at: :desc).limit(10)
  end

  def about
  end

  def author
  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

	def create
		post = Post.find(params[:post_id])
		comment = current_customer.post_comments.new(post_comment_params)
		comment.post_id = post.id
		comment.save
		redirect_to post_path(post)
	end

	def destroy
		PostComment.find_by(id: params[:id], post_id: params[:post_id]).destroy
		redirect_to post_path(params[:post_id])
	end

	private
	def post_comment_params
		params.require(:post_comment).permit(:comment)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  	@posts = Post.all
  end

  def all
  	@posts = Post.where(customer_id: params[:customer_id])
    @customer = Customer.find(params[:customer_id])
  end

  def ranking
    @posts = Post.joins(:favorites).group("favorites.post_id").order("count(favorites.id) desc").limit(10)
  	#@posts = Post.all.sort {|a,b| b.favorited_customers.count <=> a.favorited_customers.count}.slice(0,10)
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = current_customer.posts.new(post_params)
  	@post.rate = 0 if @post.rate.blank? #後置if
  	if @post.save
  		redirect_to post_path(@post)
  	else
  		render 'new'
  	end
  end

  def show
  	@post = Post.find(params[:id])
  	@customer = Customer.find_by(id: @post.customer_id)
    @post_comment = PostComment.new
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])
  	if @post.update(post_params)
  		redirect_to post_path(@post)
  	end
  end

  def destroy
  	@post = Post.find(params[:id])
    @post.destroy
    redirect_to mypage_customer_path(current_customer)
  end

  private
  def post_params
  	params.require(:post).permit(
  		:title, :body, :product_name, :bay_day, :price, :product_image, :rate)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/index.html.erb
<div class="container bookmark_container">
	<div class="bookmark_title">
		<p class="bookmark_title_1">Favorites List</p>
		<p class="bookmark_title_2">お気に入りリスト</p>
	</div>

	<div class="bookmark_box">
		<table>
			<tr>
				<th></th><th>タイトル</th><th></th><th>ユーザネーム</th><th></th>
			</tr>
			<% @bookmarks.each do |bookmark| %>
				<tr>
					<td>
						<%= attachment_image_tag bookmark.post, :product_image, :fill, 100, 100, class: "bookmark_img_1", fallback: "no_image_square.jpg", size: '100x100' %>
					</td>
					<td>
						<%= bookmark.post.title %>
					</td>
					<td>
						<%= attachment_image_tag current_customer, :profile_image, :fill, 100, 100, class: "img-circle bookmark_img_2", fallback: "no_image_square.jpg", size: '100x100' %>
					</td>
					<td>
						<%= bookmark.post.customer.handle_name %>
					</td>
					<td>
						<%= link_to "リストから外す", bookmark_path(bookmark), method: :delete, class: "btn btn-danger btn-lg" %>
					</td>
			<% end %>
		</table>
	</div>
</div>

app/views/customers/edit.html.erb
<div class="container user_edit_container">
	<div class="user_edit_title">
		<p class="user_edit_title_1">User Edit</p>
		<p class="user_edit_title_2">ユーザ情報編集</p>
	</div>

	<div class="row">
		<%= form_for(@customer) do |f| %>
			<div class="col-xs-3 user_edit_img">
				<%= attachment_image_tag @customer, :profile_image, :fill, 350, 350, class: "img-circle pull-left user_image_edit", fallback: "no_image_square.jpg" %>
				<%= f.attachment_field :profile_image, class: "user_edit_img_button" %>
			</div>

			<div class="pull-right user_edit_box">
				<div class="user_edit_item">
					<span>氏名</span>
					<%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %>
					<%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %>
				</div>
				<div class="user_edit_item">
					<span>カナ</span>
					<%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana" %>
					<%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana" %>
				</div>
				<div class="user_edit_item">
					<span>表示名</span>
					<%= f.text_field :handle_name, autofocus: true, autocomplete: "handle_name" %>
				</div>
				<div class="user_edit_item">
					<span>メールアドレス</span>
					<%= f.email_field :email, autofocus: true, autocomplete: "email" %>
				</div>

				<div class="user_edit_actions">
		          <%= f.submit "更新する", class: "btn btn-success btn-md" %>
		        </div>
		    </div>
	    <% end %>
	</div>

	<div class="user_edit_actions2">
      <% if customer_signed_in? && @customer.id == current_customer.id %>
        <%= link_to '退会する', unsubscribe_customer_path(@customer), class: "btn btn-danger btn-md" %>
      <% end %>
	</div>
</div>

app/views/customers/index.html.erb
<div class="container user_index_container">
	<div class="user_index_title">
		<p class="user_index_title_1">User List</p>
		<p class="user_index_title_2">ユーザ一覧</p>
	</div>

	<div class="user_index_box">
		<% @customers.each do |customer| %>
			<%= link_to customer_path(customer) do %>
				<div class="user_index_item">
					<div class="user_index_img">
						<%= attachment_image_tag customer, :profile_image, :fill,150, 150, class: "img-circle", fallback: "no_image_square.jpg", size: '150x150' %>
					</div>
					<div class="user_index_name">
						<%= customer.handle_name %>
					</div>
				</div>
			<% end %>
		<% end %>
	</div>
</div>

app/views/customers/mypage.html.erb
<div class="container mypage_container">
	<div class="mypage_title">
		<p class="mypage_title_1">My Page</p>
		<p class="mypage_title_2">マイページ</p>
	</div>

	<div class="mypage_box">
		<div class="mypage_list">
			<%= link_to '投稿する', new_post_path, class: 'mypage_item' %>
		</div>
		<div class="mypage_list">
			<%= link_to '自分の投稿', all_posts_path(customer_id: @customer.id), class: 'mypage_item' %>
		</div>
		<div class="mypage_list">
			<%= link_to 'ユーザ情報', customer_path(current_customer), class: 'mypage_item' %>
		</div>
		<div class="mypage_list">
			<%= link_to 'お気に入りリスト', bookmarks_path, class: 'mypage_item' %>
		</div>
	</div>
</div>

app/views/customers/show.html.erb
<div class="container user_information_container">
	<div class="user_information_title">
		<p class="user_information_title_1">
			User Information
		</p>
		<p class="user_information_title_2">
		 	ユーザ情報
		</p>
	</div>

	<% if @customer.id == current_customer.id %>
		<div class="row">
			<div class="user_information_item">
				<%= attachment_image_tag @customer, :profile_image, :fill, 350, 350, class: "img-circle pull-left user_image_show", fallback: "no_image_square.jpg" %>
			</div>

			<div class="col-xs-5 user_information_box">
				<table>
					<tr>
						<td>氏名</td>
						<td><%= @customer.last_name %> <%= @customer.first_name %></td>
					</tr>
					<tr>
						<td>カナ</td>
						<td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
					</tr>
					<tr>
						<td>表示名</td>
						<td><%= @customer.handle_name %></td>
					</tr>
					<tr>
						<td>メールアドレス</td>
						<td><%= @customer.email %></td>
					</tr>
					<tr>
						<td>投稿数</td>
						<td><%= @post.count %>件</td>
					</tr>
				</table>
			</div>
		</div>

		<div class="user_information_button">
			<%= link_to '編集する', edit_customer_path, class: "btn btn-success btn-md" %>
		</div>

	<% else %>

		<div class="row">
			<div class="user_information_item">
				<%= attachment_image_tag @customer, :profile_image, :fill, 350, 350, class: "img-circle pull-left user_image_show", fallback: "no_image_square.jpg" %>
			</div>

			<div class="col-xs-5 user_information_box_other">
				<table>
					<tr>
						<td>表示名</td>
						<td><%= @customer.handle_name %></td>
					</tr>
					<tr>
						<td>投稿数</td>
						<td><%= @post.count %>件</td>
					</tr>
				</table>
			</div>

			<div class="pull-right user_information_link">
				<%= link_to 'このユーザの投稿一覧へ >>>', all_posts_path(customer_id: @customer.id) %>
			</div>
		</div>
	<% end %>
</div>

app/views/customers/thanks.html.erb
<div class="container thanks">
	<p>退会処理が完了致しました。</p>
	<p>またのご利用をお待ちしております！</p>

	<div class="thanks_item">
		<%= link_to 'Topページへ', root_path %>
	</div>
</div>

app/views/customers/unsubscribe.html.erb
<div class="container user_unsubscribe_container">
	<div class="user_unsubscribe_title">
		<p>本当に退会しますか？</p>
	</div>

	<div class="user_unsubscribe_box">
		<p>はいを選択されますと、登録情報・投稿・コメント等全ての情報が失われます。</p>
	</div>

	<div class="user_unsubscribe_item">
		<div class="user_unsubscribe_button">
			<%= link_to 'はい', unsubscribe_customer_path(@customer), method: :patch, data: {confirm: "退会されますと、登録情報・投稿・コメント等全ての情報が失われます。本当に退会されますか？"}, class: "btn btn-danger btn-lg" %>
		</div>
		<div class="user_unsubscribe_button2">
			<%= link_to '退会しない', edit_customer_path, class: "btn btn-primary btn-lg" %>
		</div>
	</div>
</div>

app/views/homes/about.html.erb
<div class="container about_container">
	<div class="about_message1">
		<!-- <h1 style="color: #b7282c;">エレピア</h1> -->
		<p class="about_message1_a">エレピア</p>
		<!-- <h3 style="padding-top: 2%;">って？</h3> -->
		<p class="about_message1_b">って？</p>
	</div>
	<div class="about_message2">
		<p>エレピアは、女性向けの電化製品に特化したインスタライクのシェアサービスです。</p>
		<p>「オシャレでカワイイ電化製品はたくさんあるから、もっと知って欲しい！」</p>
		<p>という願いから生まれました。</p>
		<p>こちらのサイトは写真の投稿やレビュー、他のユーザがオススメしている</p>
		<p>電化製品を見ることができ、人気のランキングなどもあります。</p>
	</div>
	<div class="about_line1"></div>
</div>

<div class="container about_container2">
	<div class="row row1">
		<div class="top_image2">
			<%= image_tag('PF_img_c_1.png', style: "width: 100%;") %>
		</div>
		<!-- <div class="top_text2">
			<P>オススメの電化製品を投稿しよう！<br>
			投稿はマイページから行えます！</P>
		</div> -->
	</div>

	<div class="row row2">
		<div class="top_image3">
			<!-- <P class="top_text3">いいねしたり、他のユーザが投稿した製品を<br>
			お気に入りリストに追加もできます！</P> -->
			<%= image_tag('PF_img_c_3.png', style: "width: 100%;") %>
		</div>
	</div>
</div>

app/views/homes/author.html.erb
<div class="container author_container">
	<div class="author_title">
		<p class="author_title_1">
			Author
		</p>
		<p class="author_title_2">
		 	作成者
		</p>
	</div>

	<div class="author_box">
		<div class="author_image">
			<%= image_tag('IMG_3341.jpg', style: "width: 400px;") %>
		</div>
		<div class="author_message">
			<table>
				<tr>
					<td>氏名</td>
					<td>猪原 将志(Masashi Inohara)</td>
				</tr>
				<tr>
					<td>好きな食べ物</td>
					<td>トマト</td>
				</tr>
				<tr>
					<td>好きな色</td>
					<td>深めの赤</td>
				</tr>
				<tr>
					<td>趣味</td>
					<td>アニメ鑑賞、ウィンドウショッピング、写真</td>
				</tr>
			</table>
		</div>

		<div class="author_message2">
			<p>コメント:<br>
				こんにちは。作成者のイノハラと申します。<br>
				約１ヶ月間のポートフォリオを終えた感想や<br>
				意識したこと、後悔などを軽くお話します。<br>
			</p>
		</div>
		<div class="author_message3">
			<p>まず、今回私が扱ったテーマが<br>
				「電化製品」と「女性」でした。<br>
				実際にポートフォリオを作る上で、<br>
				ありふれたテーマでは自分が作っていて<br>
				面白くないと思って、このテーマにしました。<br>
				ベースにあるのはありふれた投稿型のサービスですが、<br>
				そこにあまり馴染みのないテーマが加わることで、<br>
				ちょっとした可能性を自分にも作品にも<br>見出せるのではないかと考えました。<br>
				自身の技術力ではここまでが限界でしたが、<br>
				管理者側の作成や複数画像の投稿など、<br>
				やりたいことはたくさんありました。<br>
				時間の管理はとても難しく、期日までに終わらせる<br>
				ということはこの先も必ず直面することなので、<br>
				そういったことも学べたことに感謝しています。
			</p>
		</div>
		<div class="author_message4">
			<p>デザインに関しては女性らしさを感じる清潔感や<br>
				見やすいように空白を意識して作成しました。<br>
				全体的な色味に関して、一部を除いて基本色は<br>
				赤、ピンク、白で統一させています。<br>
				ターゲットが20~40代の女性をイメージしているのと<br>
				女性向けの電化製品の色味に近い配色にしています。
			</p>
		</div>

		<div class="author_image2">
		<%= image_tag('PF_logo_proto2.png', style: "width: 700px; height: 455px;") %>
		</div>
	</div>
</div>

app/views/homes/top.html.erb
<div id="container">
	<div id="theTarget">
		<div class="image1"></div>
		<div class="image2"></div>
		<div class="image3"></div>
		<div class="image4"></div>
	</div>
	<div class="top_image">
		<%= image_tag 'PF-logo1.png', class: "top_image_logo" %>
	</div>
	<div class="top_text">
		<p>ようこそ</p>
		<p>エレピアへ</p>
	</div>
</div>

<% if customer_signed_in? %>

	<div class="container">
		<div class="top_title">
			<p class="top_title_1">New Post List</p>
			<p class="top_title_2">最新投稿一覧</p>
		</div>

		<div class="post_top_box">
			<% @posts.each do |post| %>
	    		<%= link_to post_path(post) do %>
	      			<div class="post_top_item">
	        			<div class="index_img">
	          				<%= attachment_image_tag post, :product_image, :fill, 200, 200, class: "post_index_img", fallback: "no_image_square.jpg", size: '200x200' %>
	       				</div>
	        			<div class="top_list_box">
	          				<div class="post_top_name">
	            				<%= post.title %>
	         				</div>
	          				<div class="post_top_day">
	          					<%= l post.created_at, format: :short %>
	          				</div>
	        			</div>
	      			</div>
	    		<% end %>
	  		<% end %>
		</div>
	</div>

<% else %>

	<div class="container">
		<div class="about_message1">
			<h1 style="color: #b7282c;">エレピア</h1><h3 style="padding-top: 2%;">って？</h3>
		</div>
		<div class="about_message2">
			<p>エレピアは、女性向けの電化製品に特化したインスタライクのシェアサービスです。</p>
			<p>「オシャレでカワイイ電化製品はたくさんあるから、もっと知って欲しい！」</p>
			<p>という願いから生まれました。</p>
			<p>こちらのサイトは写真の投稿やレビュー、他のユーザがオススメしている</p>
			<p>電化製品を見ることができ、人気のランキングなどもあります。</p>
		</div>
		<div class="about_line1"></div>
	</div>

	<div class="container">
		<div class="row row1">
			<div class="top_image2 col-xs-6">
				<%= image_tag('PF_photo.jpg', style: "width: 100%;") %>
			</div>
			<div class="top_text2 col-xs-offset-1 col-xs-5">
				<P>オススメの電化製品を投稿しよう！<br>
			投稿はマイページから行えます！</P>
			</div>
		</div>
		<div class="row row2">
			<div class="top_text3 col-xs-offset-1 col-xs-5">
				<P>いいねしたり、他のユーザが投稿した製品を<br>
				お気に入りリストに追加もできます！</P>
			</div>
			<div class="top_image3 col-xs-6">
				<%= image_tag('PF_photo4.png', style: "width: 100%;") %>
			</div>
		</div>
		<div class="about_line2"></div>
	</div>

	<div class="container">
		<div class="top_title">
			<p class="top_title_1">New Post List</p>
			<p class="top_title_2">最新投稿一覧</p>
		</div>

		<div class="post_top_box">
			<% @posts.each do |post| %>
	    		<%= link_to post_path(post) do %>
	      			<div class="post_top_item">
	        			<div class="index_img">
	          				<%= attachment_image_tag post, :product_image, :fill, 200, 200, class: "post_index_img", fallback: "no_image_square.jpg", size: '200x200' %>
	       				</div>
	        			<div class="top_list_box">
	          				<div class="post_top_name">
	            				<%= post.title %>
	         				</div>
	          				<div class="post_top_day">
	          					<%= l post.created_at, format: :short %>
	          				</div>
	        			</div>
	      			</div>
	    		<% end %>
	  		<% end %>
		</div>
	</div>
<% end %>

app/views/posts/all.html.erb
<div class="container post_index_container">
	<div class="post_index_title">
    <p class="post_index_title_1">Posts List</p>
    <p class="post_index_title_2"><%= @customer.handle_name %>さんの投稿一覧</p>
  </div>

	<div class="post_index_box">
		<% @posts.each do |post| %>
			<%= link_to post_path(post) do %>
	      		<div class="post_index_item">
	        		<div class="index_img">
	          			<%= attachment_image_tag post, :product_image, :fill, 200, 200, class: "post_index_img", fallback: "no_image_square.jpg", size: '200x200' %>
	       			</div>
	        		<div class="list_box">
	          			<div class="post_index_name">
	            			<%= post.title %>
	         			</div>
	          			<div class="post_index_day">
	          				<%= l post.created_at, format: :short %>
	          			</div>
	        		</div>
	      		</div>
	    	<% end %>
		<% end %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container post_show_container">
	<div class="post_show_title">
		<p class="post_show_title_1">Post Details</p>
		<p class="post_show_title_2">投稿詳細</p>
	</div>

	<div class="post_show_user_box">
		<%= link_to customer_path(@customer) do %>
			<div class="user_img_tag">
				<p><%= @customer.handle_name %></p>
				<%= attachment_image_tag @customer, :profile_image, :fill, 80, 80, class: "img-circle user_img_show", fallback: "no_image_square.jpg" %>
			</div>
		<% end %>
	</div>

	<div class="post_show_box">
		<div class="post_show_img_box">
			<%= attachment_image_tag @post, :product_image, :fill, 400, 400, class: "post_show_img", fallback: "no_image_square.jpg" %>
		</div>

		<div class="post_show_form">
			<div class="post_show_item">
				<p class="p_item">タイトル:</p>
				<p><%= @post.title %></p>
			</div>
			<div class="post_show_item">
				<p class="p_item">商品名:</p>
				<p><%= @post.product_name %></p>
			</div>
			<div class="post_show_item_a">
				<div class="post_show_in_item_a">
					<p class="p_item">購入日:</p>
					<p><%= @post.bay_day %></p>
				</div>
				<div class="post_show_in_item_b">
					<p class="p_item">購入時価格:</p>
					<p>¥<%= @post.price.to_s(:delimited) %></p>
				</div>
				<div class="post_show_in_item_c">
					<p class="p_item">投稿日:</p>
					<p><%= l @post.created_at, format: :short %></p>
				</div>
			</div>
			<div class="post_show_item_b">
				<p class="p_item">コメント:</p>
				<p><%= @post.body %></p>
			</div>

			<div class="post_show_item_c">
				<div class="post_show_in_item_d">
					<p class="p_item_a">いいね</p>
					<% if @post.favorited_by?(current_customer) %>
					  <td>
					  	<%= link_to post_favorites_path(@post), method: :delete do %>
					  	  <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
					  	  <%= @post.favorites.count %>
					  	<% end %>
					  </td>
					<% else %>
					  <td>
					  	<%= link_to post_favorites_path(@post), method: :post do %>
					  	  <span class="glyphicon glyphicon-heart-empty" aria-hidden="true" ></span>
					  	  <%= @post.favorites.count %>
					  	<% end %>
					  </td>
					<% end %>
				</div>
				<div class="post_show_in_item_e">
					<p class="p_item">評価</p>
					<div id="star-rate"></div>
				</div>
			</div>
		</div>
	</div>

	<% if @post.customer == current_customer %>
		<div class="post_show_action">
			<%= link_to '編集する', edit_post_path(@post), class: "btn btn-primary btn-md" %>
			<%= link_to "削除する", post_path(@post), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-danger btn-md destroy_post_#{@post.id}" %>
		</div>
	<% else %>
		<div class="post_show_action">
			<%= link_to 'お気に入りへ追加', bookmarks_path(post_id: @post.id), method: :post, class: "btn btn-primary btn-md" %>
		</div>
	<% end %>

	<div class="post_show_comments">
		<p>コメント一覧</p>
		<ul class="container">
			<% @post.post_comments.each do |post_comment| %>
				<li>
					<div class="comment">
						<div class="comment_entry">
							<%= post_comment.comment %>
						</div>
						<div class="comment_box">
							<div class="comment_name">
								- <%= post_comment.customer.handle_name %> -
							</div>
							<div class="comment_date">
								<%= post_comment.created_at.strftime('%Y/%m/%d') %>
							</div>
							<% if post_comment.customer == current_customer %>
								<div class="comment_d_button">
									<%= link_to "コメントを削除する", post_post_comment_path(post_comment.post, post_comment), method: :delete, class: "btn btn-danger btn-sm" %>
								</div>
							<% end %>
						</div>
					</div>
				</li>
			<% end %>
		</ul>
	</div>

	<%= form_for [@post, @post_comment] do |f| %>
		<div class="comment_form">
			<div class="post_comment_box">
				<p>コメント投稿</p>
				<%= f.text_area :comment, class: "comment_area_show", placeholder: "50文字以内" %>
				<%= f.submit "コメントする", class: "btn btn-base-1 btn-md" %>
			</div>
		</div>
	<% end %>
</div>

<script>
	$('#star-rate').raty({
	    size     : 36,
	    starOff:  '<%= asset_path('star-off.png') %>',
	    starOn : '<%= asset_path('star-on.png') %>',
	    starHalf: '<%= asset_path('star-half.png') %>',
	    scoreName: 'post[rate]',
	    half: true,
	    readOnly: true,
	    score: <%= @post.rate %>,
	});
</script>