config/routes.rb
Rails.application.routes.draw do

  get 'reviews/create'
	devise_for :customers

	get 'homes/top'
	root 'homes#top'

	get 'homes/about'
	get 'homes/author'

  	resources :customers, only: [:show, :edit, :update, :index] do
	  	member do
		  get 'mypage'
		  get 'unsubscribe'
		  patch 'unsubscribe'
		  get 'thanks'
		end
	end

	resources :posts do
		resources :post_comments, only: [:create, :destroy]
		resource  :favorites, only: [:create, :destroy]
		collection do
		  get 'all'
		  get 'ranking'
		end
	end

	resources :bookmarks, only: [:create, :destroy, :index]


	resources :reviews

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord

  belongs_to :customer
  belongs_to :post
  validates :customer_id, uniqueness: { scope: :post_id }

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, presence: true

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_posts, through: :bookmarks, source: :post
  has_many :post_comments, dependent: :destroy
  attachment :profile_image

end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :customer
	belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :customer
	has_many :favorites, dependent: :destroy
	has_many :favorited_customers, through: :favorites, source: :customer
	has_many :bookmarks, dependent: :destroy
	has_many :post_comments, dependent: :destroy
	attachment :product_image

	validates :rate, numericality: {
		less_than_or_equal_to: 5,
		greater_than_or_equal_to: 0
	}

	def favorited_by?(customer)
		favorites.where(customer_id: customer.id).exists?
	end

	def bookmark_by?(customer)
		bookmarks.where(customer_id: customer.id).exists?
	end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

	belongs_to :customer
	belongs_to :post

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [
			:last_name,
			:first_name,
			:last_name_kana,
			:first_name_kana,
			:handle_name
		])
	end

	def after_sign_in_path_for(reosurce)
		root_path(resource)
	end

	def after_sign_out_path_for(resource)
		root_path(resource)
	end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
  	#@customer = current_customer
  	#@bookmarks = Bookmark.where(customer_id: current_customer.id)
  	@bookmarks = Bookmark.where(customer_id: current_customer.id)
  	#@posts = Post.where(id: bookmarks)
  end

  def create
  	bookmark = current_customer.bookmarks.build(post_id: params[:post_id])
  	bookmark.customer_id = current_customer.id
    bookmark.save!
    redirect_to bookmarks_path
  end

  def destroy
  	current_customer.bookmarks.find_by(id: params[:id]).destroy!
    redirect_to bookmarks_path
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def mypage
    @customer = Customer.find(params[:id])
  end

  def show
    @customer = Customer.find(params[:id])
    @post = @customer.posts
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path(@customer)
    end
  end

  def index
    @customers = Customer.all
  end

  def unsubscribe
    @customer = Customer.find(params[:id])
    if request.patch?
      @customer.update(is_deleted: true)
      reset_session
      redirect_to thanks_customer_path
    end
  end

  def thanks
  end

  def customer_params
    params.require(:customer).permit(
      :last_name, :first_name, :last_name_kana, :first_name_kana, :handle_name, :email, :is_deleted, :profile_image)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
  	post = Post.find(params[:post_id])
	favorite = current_customer.favorites.new(post_id: post.id)
	favorite.save
	redirect_back(fallback_location: root_path)
  end

  def destroy
  	post = Post.find(params[:post_id])
	favorite = current_customer.favorites.find_by(post_id: post.id)
	favorite.destroy
	redirect_back(fallback_location: root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  	@posts = Post.order(created_at: :desc).limit(10)
  end

  def about
  end

  def author
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  	@posts = Post.all
  end

  def all
  	@posts = Post.where(customer_id: params[:customer_id])
    @customer = Customer.find(params[:customer_id])
  end

  def ranking
    @posts = Post.joins(:favorites).group("favorites.post_id").order("count(favorites.id) desc").limit(10)
  	#@posts = Post.all.sort {|a,b| b.favorited_customers.count <=> a.favorited_customers.count}.slice(0,10)
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = current_customer.posts.new(post_params)
  	@post.rate = 0 if @post.rate.blank? #後置if
  	if @post.save
  		redirect_to post_path(@post)
  	else
  		render 'new'
  	end
  end

  def show
  	@post = Post.find(params[:id])
  	@customer = Customer.find_by(id: @post.customer_id)
    @post_comment = PostComment.new
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])
  	if @post.update(post_params)
  		redirect_to post_path(@post)
  	end
  end

  def destroy
  	@post = Post.find(params[:id])
    @post.destroy
    redirect_to mypage_customer_path(current_customer)
  end

  private
  def post_params
  	params.require(:post).permit(
  		:title, :body, :product_name, :bay_day, :price, :product_image, :rate)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elepeer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="drawer drawer--left">
    <div id="wrapper">
      <header>
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="header-container">
              <div role="banner">
                <button type="button" class="drawer-toggle drawer-hamburger">
                  <span class="sr-only">toggle navigation</span>
                  <span class="drawer-hamburger-icon"></span>
                </button>
                  <nav class="drawer-nav" role="navigation">
                    <ul class="drawer-menu">
                      <% if customer_signed_in? %>
                        <li class="drawer-menu-item">
                          <%= link_to 'TOP', root_path, class: 'item' %></li>
                        <li class="drawer-menu-item">
                          <%= link_to 'About', homes_about_path, class: 'item' %></li>
                        <li class="drawer-menu-item">
                          <%= link_to '投稿一覧', posts_path, class: 'item' %></li>
                        <li class="drawer-menu-item">
                          <%= link_to 'ユーザ一覧', customers_path, class: 'item' %></li>
                        <li class="drawer-menu-item">
                          <%= link_to 'ランキング', ranking_posts_path, class: 'item' %></li>
                        <li class="drawer-menu-item">
                          <%= link_to 'マイページ', mypage_customer_path(current_customer), class: 'item' %></li>
                        <li class="drawer-menu-item">
                          <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'item' %></li>

                      <% else %>

                        <li class="drawer-menu-item">
                          <%= link_to 'TOP', root_path, class: 'item' %></li>
                        <li class="drawer-menu-item">
                          <%= link_to 'About', homes_about_path, class: 'item' %></li>
                        <li class="drawer-menu-item">
                          <%= link_to '投稿一覧', posts_path, class: 'item' %></li>
                        <li class="drawer-menu-item">
                          <%= link_to 'ユーザ一覧', customers_path, class: 'item' %></li>
                        <li class="drawer-menu-item">
                          <%= link_to 'ランキング', ranking_posts_path, class: 'item' %></li>
                        <li class="drawer-menu-item">
                          <%= link_to '新規登録', new_customer_registration_path, class: 'item' %></li>
                        <li class="drawer-menu-item">
                          <%= link_to 'ログイン', new_customer_session_path, class: 'item' %></li>

                      <% end %>
                    </ul>
                  </nav>
            </div>
            <div class="logo">
              <%= link_to image_tag('PF-logo1.png', style: "height: 50px;"), root_path %>
            </div>
            <% if customer_signed_in? %>
              <p class="navbar-text navbar-right header-message">ようこそ <%= current_customer.handle_name %> さん!</p>
            <% end %>
          </div>
        </nav>
      </header>

      <main>
        <%= yield %>
      </main>

      <footer>
        <p class="footer_message">こちらはポートフォリオのサイトとなっております。<br>
          ©︎iNO.inc<br>
          製作者情報<br>
          <%= link_to 'Created by iNO', homes_author_path, style: "color: #b7282c;" %>
        </p>
      </footer>
    </div>
  </body>
</html>